### ISSUE TITLE
wordcloud site

### ISSUE THREAD

**Issue by myidsan** [Mark-Jung/shitnews_api#5]
1. Scripts are returning appropriate data. 

2. Found a good wordcloud site [https://www.wordclouds.com/], but don't know how to input the script return to the text box. --> Figure this out plz
(Currently output format of script reflects the site syntax.
ex> 12 health
11 trump
10 ’
7 review
6 care
6 world
5 mexico
5 speech
4 plan
4 lawyer
4 reporter
4 scoop
4 industry
4 morning
4 briefing
4 fashion
3 bill
3 edition
3 today
3 waithe
3 life
3 history

**Comment by Mark-Jung** [comment]
I wouldn't try to use selenium to automate the process. I'd use the site's api directly. If the site does have an api, their input format should be somewhat documented.

**Comment by Mark-Jung** [comment]
never mind. The core of this website is open sourced, written in js. This means we can just add this to our website. Also, now our api doesn't need any aws hosting or slow ass response time.  Fantastic!! Also, FAQs are really helpful. [https://github.com/timdream/wordcloud] is the github page to the api. It said it's a spinoff of the HTML 5 wordcloud project, which means we can probably try to write our own in the future.

**Comment by Mark-Jung** [comment]
I'll start working on the integration of your script to the current backend. Can you get started on the site design? @myidsan
